config/routes.php
<?php

/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
//    $routes->connect('/', ['controller' => 'Users', 'action' => 'view']);
    $routes->connect('/', ['controller' => 'Home', 'action' => 'index']);
    $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
    $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);


    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

Router::extensions('json', 'xml');

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Tipodocumento.php
<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Tipodocumento Entity
 *
 * @property int $id
 * @property int $grupodocumento_id
 * @property string $descricao
 * @property int $exige_competencia
 * @property int $exige_exercicio
 * @property \Cake\I18n\Time $last_update
 * @property bool $status
 *
 * @property \App\Model\Entity\Documento[] $documentos
 */
class Tipodocumento extends Entity {

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

}

src/Model/Table/TipodocumentosTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Tipodocumentos Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Grupodocumentos
 * @property \Cake\ORM\Association\HasMany $Documentos
 * //@property \Cake\ORM\Association\HasMany $Subtipodocumentos
 *
 * @method \App\Model\Entity\Tipodocumento get($primaryKey, $options = [])
 * @method \App\Model\Entity\Tipodocumento newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Tipodocumento[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Tipodocumento|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Tipodocumento patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Tipodocumento[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Tipodocumento findOrCreate($search, callable $callback = null)
 */
class TipodocumentosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('tipodocumentos');
        $this->displayField('descricao');
        $this->primaryKey('id');

        $this->belongsTo('Grupodocumentos', [
            'foreignKey' => 'grupodocumento_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Documentos', [
            'foreignKey' => 'tipodocumento_id'
        ]);
//        $this->hasMany('Subtipodocumentos', [
//            'foreignKey' => 'tipodocumento_id'
//        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('descricao', 'create')
            ->notEmpty('descricao');

        $validator
            ->dateTime('last_update')
            ->allowEmpty('last_update');

        $validator
            ->boolean('status')
            ->allowEmpty('status');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['grupodocumento_id'], 'Grupodocumentos'));

        return $rules;
    }
}

src/Controller/TipodocumentosController.php
<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * Tipodocumentos Controller
 *
 * @property \App\Model\Table\TipodocumentosTable $Tipodocumentos
 */
class TipodocumentosController extends AppController {

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index() {
        $this->paginate = [
            'contain' => 'Grupodocumentos'
        ];

        $query = $this->Tipodocumentos->find()->innerJoinWith('Grupodocumentos');

        if ($this->request->is('post') && !empty($this->request->data('termo-pesquisa'))) {
            $query->orWhere(["Grupodocumentos.descricao like '%" . $this->request->data('termo-pesquisa') . "%'"]);
            $query->orWhere(["Tipodocumentos.descricao like '%" . $this->request->data('termo-pesquisa') . "%'"]);
        }


        $tipodocumentos = $this->paginate($query->orderAsc('Tipodocumentos.descricao'));

        $this->set(compact('tipodocumentos'));
        $this->set('_serialize', ['tipodocumentos']);
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function ajax($grupodocumento_id = null) {// retorna os grupos, de acordo com o setor passado por parametro, e codifica para o tipo json 
        $this->viewBuilder()->layout('ajax');
        $retorno = $this->Tipodocumentos->find('list')->where(['grupodocumento_id' => $grupodocumento_id])->order(['descricao' => 'ASC']);

        $tpview = 'list';
        $this->set(compact('retorno', 'tpview'));
        $this->set('_serialize', ['retorno', 'tpview']);
        $this->render('ajax');
    }

    /**
     * View method
     *
     * @param string|null $id Tipodocumento id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null) {
        $tipodocumento = $this->Tipodocumentos->get($id, [
            'contain' => ['Documentos', 'Grupodocumentos', 'Documentos.Empresas', 'Documentos.Funcionarios']
        ]);

        $this->set('tipodocumento', $tipodocumento);
        $this->set('_serialize', ['tipodocumento']);
    }

    /**
     * verificacompetenciaexercicio method
     *
     * @return \Cake\Network\Response|null
     */
    public function verificacompetenciaexercicio($id) {
        $this->viewBuilder()->layout('ajax');
        $documento = $this->Tipodocumentos->get($id);
        $competencia = $documento->exige_competencia;
        $exercicio = $documento->exige_exercicio;
        $this->set(compact('competencia', 'exercicio'));
        $this->set('_serialize', ['retorno', 'competencia', 'exercicio']);
        $this->render('ajax');
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add() {
        $tipodocumento = $this->Tipodocumentos->newEntity();
        if ($this->request->is('post')) {
            $tipodocumento = $this->Tipodocumentos->patchEntity($tipodocumento, $this->request->data);
            if ($this->Tipodocumentos->save($tipodocumento)) {
                $this->Flash->success(__('Salvo com sucesso.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('Erro ao salvar tipo de documento. Por favor, tente novamente.'));
            }
        }

        $grupodocumentos = $this->Tipodocumentos->Grupodocumentos->find('list', ['limit' => 200]);
        $this->set(compact('tipodocumento', 'grupodocumentos'));
        $this->set('_serialize', ['tipodocumento']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Tipodocumento id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null) {
        $tipodocumento = $this->Tipodocumentos->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $tipodocumento = $this->Tipodocumentos->patchEntity($tipodocumento, $this->request->data);
            if ($this->Tipodocumentos->save($tipodocumento)) {
                $this->Flash->success(__('Tipo de documento atualizado com sucesso.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('Erro ao salvar tipo de documento. Por favor, tente novamente.'));
            }
        }

        $grupodocumentos = $this->Tipodocumentos->Grupodocumentos->find('list', ['limit' => 200]);
        $this->set(compact('tipodocumento', 'grupodocumentos'));
        $this->set('_serialize', ['tipodocumento']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Tipodocumento id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null) {
        $this->request->allowMethod(['post', 'delete']);
        $tipodocumento = $this->Tipodocumentos->get($id);
        if ($this->Tipodocumentos->delete($tipodocumento)) {
            $this->Flash->success(__('Tipo de documento removido com sucesso.'));
        } else {
            $this->Flash->error(__('Erro ao remover tipo de documento. Por favor, tente novamente.'));
        }

        return $this->redirect($this->request->referer());
    }

}

src/Template/Tipodocumentos/add.ctp
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">         
            <div class="x_title">
                <h2>Cadastro de Documento <small>* campos obrigatórios</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#"></a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <?= $this->Form->create($tipodocumento, ["class" => "form-horizontal form-label-left"]) ?>
                <?= $this->Flash->render() ?>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="razao">Grupo de Documento <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('grupodocumento_id', [ "class" => "form-control col-md-7 col-xs-12", 'label' => false, 'options' => $grupodocumentos]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="razao">Descrição <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('descricao', [ "class" => "form-control col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="exige_competencia">Necessita informar competência? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('exige_competencia', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="exige_exercicio">Necessita informar exercício? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('exige_exercicio', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="funcionario">É referente a um funcionário? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('funcionario', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="reemissao">Poderá ser solicitado a remissão? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('reemissao', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-success">Cadastrar</button>

                        <?= $this->Html->link(__('Voltar'), $backlink, ['class' => "btn btn-primary"]) ?> 
                    </div>
                </div>
                <?= $this->Form->end() ?>
            </div>
        </div>
    </div>
</div>

src/Template/Tipodocumentos/edit.ctp
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">         
            <div class="x_title">
                <h2>Atualizar informações do documento. <small>* campos obrigatórios</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#"></a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <?= $this->Form->create($tipodocumento, ["class" => "form-horizontal form-label-left"]) ?>
                <?= $this->Flash->render() ?>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="razao">Grupo de Documento <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('grupodocumento_id', [ "class" => "form-control col-md-7 col-xs-12", 'label' => false, 'options' => $grupodocumentos]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="razao">Descrição <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('descricao', [ "class" => "form-control col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="exige_competencia">Necessita informar competência? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('exige_competencia', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="exige_exercicio">Necessita informar exercício? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('exige_exercicio', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="funcionario">É referente a um funcionário? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('funcionario', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="reemissao">Poderá ser solicitado a remissão? <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <?= $this->Form->input('reemissao', [ "class" => "form-control flat col-md-7 col-xs-12", 'label' => false]); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-success">Atualizar</button>

                        <?= $this->Html->link(__('Voltar'), $backlink, ['class' => "btn btn-primary"]) ?> 
                    </div>
                </div>
                <?= $this->Form->end() ?>
            </div>
        </div>
    </div>
</div>

src/Template/Tipodocumentos/view.ctp
<div class="page-title">
    <div class="title_left">
        <h3>Detalhes do Tipo de Documento</h3>
    </div>
</div>
<div class="clearfix"></div>



<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="green"><i class="fa fa-file"></i> Detalhes do Documento <?= h($tipodocumento->descricao) ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a> </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="project_detail">
                        <p class="title">Grupo de Documento</p>
                        <p><?= $tipodocumento->grupodocumento->descricao ?></p>

                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="project_detail">
                        <p class="title">Ultima Atualização</p>
                        <p><?= $tipodocumento->last_update; ?></p>
                        <p class="title">Status</p>
                        <p><?= $tipodocumento->status ? 'Ativo' : 'Inativo'; ?></p>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                            <?= $this->Html->link("Voltar", $backlink, ['class' => "btn btn-default"]) ?>
                            <?= $this->Html->link("Editar", ['action' => 'edit', $tipodocumento->id], ['class' => "btn btn-primary"]) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php
        if (!empty($tipodocumento->documentos)) {
            ?>
            <div class="x_panel">
                <div class="x_title">
                    <h2 class="green"><i class="fa fa-file"></i> Documentos Relacionados</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a> </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped jambo_table bulk_action">
                            <thead>
                                <tr class="headings">
                                    <th>
                                        <input type="checkbox" id="check-all" class="flat">
                                    </th>
                                    <th scope="col" class="column-title"><?= __('Empresa') ?></th>
                                    <th scope="col" class="column-title"><?= __('Funcionário') ?></th>
                                    <th scope="col" class="column-title"><?= __('Enviado') ?></th>
                                    <th></th>
                                    <th class="bulk-actions" colspan="7">
                                        <a class="antoo" style="color:#fff; font-weight:500;">( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                    </th>
                                    <th scope="col" class="column-title no-link"><span class="nobr"></span></th>
                                </tr>
                            </thead>
                            <tbody>

                                <?php
                                $cor = 'even';
                                foreach ($tipodocumento->documentos as $documento) {
                                    ?>

                                    <tr class="<?= $cor ?> pointer">
                                        <td class="a-center ">
                                            <input type="checkbox" class="flat" name="table_records">
                                        </td>
                                        <td><?= $this->Html->link($documento->empresa->fantasia, ['controller' => 'Empresas', 'action' => 'view', $documento->empresa->id]) ?></td>
                                        <td><?= $documento->funcionario ? $this->Html->link($documento->funcionario->nome, ['controller' => 'Funcionarios', 'action' => 'view', $documento->funcionario->id]) : '---' ?></td>
                                        <td><?= $documento->dt_enviado ?></td>
                                        <td  class=" last">
                                            <div class="btn-group">
                                                <?= $this->Html->link(__('Visualizar'), ['controller' => 'Documentos', 'action' => 'view', $documento->id], ['class' => "btn btn-primary btn-xs"]) ?>
                                                <?= $this->Html->link(__('Editar'), ['controller' => 'Documentos', 'action' => 'edit', $documento->id], ['class' => "btn btn-info btn-xs"]) ?>
                                                <?= $this->Form->postLink(__('Deletar'), ['controller' => 'Documentos', 'action' => 'delete', $documento->id], ['class' => "btn btn-danger btn-xs", 'confirm' => __('Deseja mesmo remover o documento #{0}?', $documento->id)]) ?>

                                            </div>
                                        </td>
                                    </tr>
                                    <?php
                                    $cor = $cor == 'even' ? 'odd' : 'even';
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</div>